# Name for this set of automated instructions
name: Run JavaScript Tests

# --- When should this run? ---
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# --- What jobs should be done? ---
jobs:
  # We'll define one job called 'test'
  test:
    # Use a standard virtual computer provided by GitHub (Ubuntu Linux)
    runs-on: ubuntu-latest

    # --- What steps are in the 'test' job? ---
    steps:
      # Step 1: Download your code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Use cache since we expect package.json / package-lock.json
          cache: 'npm'

      # Step 3: Install dependencies (usually needed for test runners)
      - name: Install dependencies
        run: npm install

      # Step 4: Attempt to run tests using the standard 'npm test' command
      - name: Run tests (placeholder)
        # This tries the standard 'npm test' command.
        # If no test script is defined in package.json or no tests are found,
        # it will likely fail. The '|| echo ...' part makes the step succeed anyway
        # by just printing a message if the test command itself fails.
        run: npm test || echo "No 'test' script configured in package.json or no tests found."

