name: Auto-Update Products
on:
  schedule:
    - cron: '0 0 * * *' # Updates daily at midnight
  workflow_dispatch: # Lets you manually trigger updates

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install tools
        run: pip install python-amazon-paapi openai
      - name: Fetch products
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          AMAZON_TAG: ${{ secrets.AMAZON_TAG }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: python scripts/amazon_products.py
      - name: Save changes
        run: |
          git config --global user.name "ErgAlign Bot"
          git config --global user.email "bot@ergalign.com"
          git add .
          git commit -m "Auto-update products"
          git push
