# Name for this set of automated instructions
name: Lint JavaScript Code

# --- When should this run? ---
on:
  # Run whenever code is pushed to the 'main' branch
  push:
    branches: [ main ]
  # Also run if someone suggests changes via a Pull Request to 'main'
  pull_request:
    branches: [ main ]

# --- What jobs should be done? ---
jobs:
  # We'll define one job called 'lint'
  lint:
    # Use a standard virtual computer provided by GitHub (Ubuntu Linux)
    runs-on: ubuntu-latest

    # --- What steps are in the 'lint' job? ---
    steps:
      # Step 1: Download your code from GitHub onto the virtual computer
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment (JavaScript needs this)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # The 'cache: 'npm'' line that was previously here has been removed

      # Step 3: Install ESLint globally (needed since likely not in package.json)
      - name: Install ESLint
        run: npm install -g eslint # Installs ESLint globally

      # Step 4: Run the JavaScript checker tool (ESLint)
      - name: Run ESLint
        # 'npx eslint .' tells it to run ESLint on all files in the project.
        # '--ext .js' tells it to only check files ending in .js
        # NOTE: This might still fail if ESLint needs specific configuration
        #       or if it finds actual errors in your script.js file.
        run: npx eslint . --ext .js

