# Name for this set of automated instructions
name: Lint JavaScript Code

# --- When should this run? ---
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# --- What jobs should be done? ---
jobs:
  # We'll define one job called 'lint'
  lint:
    # Use a standard virtual computer provided by GitHub (Ubuntu Linux)
    runs-on: ubuntu-latest

    # --- What steps are in the 'lint' job? ---
    steps:
      # Step 1: Download your code from GitHub onto the virtual computer
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # REMOVED cache: 'npm' from here again

      # Step 3: Install dependencies listed in package.json (including ESLint and helpers)
      - name: Install dependencies
        run: npm install # Installs devDependencies into node_modules

      # Step 4: Run ESLint (will use version installed via npm install)
      - name: Run ESLint
        run: npx eslint . --ext .js
